### PR TITLE
Add option to plot differences as percentages

### LINKED ISSUE #6: Plot differences as a percentage
Would it be possible to add a parameter to plot the difference as a percentage, instead of just raw difference values? 

[Here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4470095/#__sec6title) is an example showing this, where the y-axis would show `((data1 - data2) / mean) * 100`.

I could also submit a PR if that is appropriate

### PR DESCRIPTION
**Pull request by ltirrell**
The `blandAltman` function now has a `percentage` (boolean) option, which plots the difference as a percentage instead of raw units.

I updated the Jupyter notebook and README with a brief description, let me know if I should include anything else.

Here is an example of the percentage plot:
percentage_BA-plot
and the same data with the default:
unit_BA-plot

Closes #6

### CODE REVIEW

**Comment by ltirrell** [comment]
It seems the `expectedFailure` within `test__aa.py` is failing on [Travis](https://travis-ci.org/jaketmp/pyCompare/jobs/580600612). I also get the same `FAILED (unexpected successes=1)` error when testing locally.  I'm not really sure what this test does, any suggestion for a fix?

**Comment by jaketmp** [comment]
Does exactly what it say's on the tin - works around [this bug](https://bugs.python.org/issue29620).

Hopefully the test passing now means it's been fixed upstream, and the test can be skipped.

**Comment by ltirrell** [comment]
The tests seem to pass if i either:

1. Remove the `expectedFailure` decorator from `test__AA`
1. Remove the entire `test__AA__decoy` TestCase from `test__aa.py`
1. Remove the entire `test__aa.py` file, and put `matplotlib.use('Agg')` on the top of `test_blandAltman.py`

Any preference what I should do? I'm trying option 3 on Travis now

**Comment by jaketmp** [comment]
I think 1), just in case the bug that necessitated it resurfaces. 

Otherwise looks good - thanks!

**Comment by ltirrell** [comment]
I updated to use strategy 1, and added another test to add code coverage. Let me know if you'd want anything else

**Pull request merged**
